### ISSUE TITLE
Quicker Echarts by "Polarizing" more expressions

### ISSUE THREAD

**Issue by abstractqqq** [AdrianAntico/QuickEcharts#1]
I noticed there are lots of inefficient handling of data using Python right now, despite having Polars's expressions that can handle the operations, e.g.

```
max(dt1[YVar].max(), dt1[XVar].max(), dt1[ZVar].max())

dt.with_columns(pl.col(YVar).map_elements(math.sqrt))
```
 which can be replaced by native Polars expressions. I am opening this issue so that (1) I will remind myself to make a PR and change as much as possible, and (2) We can start by writing more Polars expressions instead of Python in future features

**Comment by AdrianAntico** [comment]
This sounds great!

**Comment by AdrianAntico** [comment]
I upgraded the transformation function operations.

**Comment by abstractqqq** [comment]
That is great! I have been very busy with other projects and doesn't have time to contribute to this
